const text = {
  minList: {
    "1":[
      [
        {value:'0',url:'1/0.png',title:'中山市吉宝置业神湾盛世游艇第一～三标段',text:'项目名称：中山市吉宝置业神湾盛世游艇第一～三标段\t甲方名称：盛世游艇会（中山）有限公司\t项目地点：中山神湾\t单方造价：462元/ ㎡\t合同总金额： 18500000元\t景观面积:40000㎡\t施工时间：2016.9.02\t项目...'},
        {value:'1',url:'1/1.png',title:'融创广深区域清远道申花园项目景观工程',text:'项目名称：融创广深区域清远道申花园项目景观工程\t甲方名称：清远市道申房地产有限公司\t项目地点：清远美林湖\t单方造价：2000元/ ㎡\t合同总金额： 14275878.89元\t景观面积:7000㎡\t施工时间：2017.09.29...'},
        {value:'2',url:'1/2.png',title:'南沙中交明珠国际项目北地块（2014NJY-9）第一标段园林景观（...',text:'项目名称：惠州奥园誉山湖项目住宅地块示范区园林工程\t甲方名称：惠州市泰华房地产开发有限公司\t项目地点：惠州湖心岛\t单方造价：674元/ ㎡\t合同总金额： 10108012.13元\t景观面积:15000㎡\t施工时间：20...'},
        {value:'3',url:'1/3.jpg',title:'惠州奥园誉山湖项目住宅地块示范区园林工程',text:'项目名称：惠州奥园誉山湖项目住宅地块示范区园林工程\t甲方名称：惠州市泰华房地产开发有限公司\t项目地点：惠州湖心岛\t单方造价：674元/ ㎡\t合同总金额： 10108012.13元\t景观面积:15000㎡\t施工时间：20...'}
      ],
      [
        {value:'4',url:'1/4.png',title:'融创广深区域恒美花园（清城首府)',text:'项目名称：融创广深区域恒美花园（清城首府）\t甲方名称：清远市恒美房地产开发有限。\t项目地点：清远\t单方造价：1200元/ ㎡\t合同总金额： 5561589.93元\t景观面积:4520㎡\t施工时间：2017.08.05\t项目业态类型...'},
        {value:'5',url:'1/5.jpg',title:'广州万达城室外主题乐园千年商都区园林景观工程',text:'项目名称：广州万达城室外主题乐园千年商都区园林景观工程\t甲方名称：广州万达文化旅游城投资有限公司\t项目地点：广州花都\t单方造价：362元/ ㎡\t合同总金额： 14479228.46元\t景观面积:40000㎡\t施工时间...'}
      ]
    ],
    "4":[
      [
        {value:'0',url:'4/0.jpg',title:'北京一号航站楼',text:'项目地址：北京市朝阳区物业类别：机场建筑类型：现代简约开  发  商：北京首都国际机场股份有限公司园林单位：深圳市四季青园林股份有限公司	北京首都国际机场是“中国第一国门...'},
        {value:'1',url:'4/1.jpg',title:'北京奥林匹克公园',text:'项目地址：北京市朝阳区物业类别：公园建筑类型：现代简约开  发  商：北京房修一建筑工程有限公司信诚智拓分公司园林单位：深圳市四季青园林股份有限公司	奥林匹克公园位于北京...'},
        {value:'2',url:'4/2.jpg',title:'佳兆业悦峰花园',text:'项目地址：深圳市龙岗区布龙路与龙颈坳路交汇处房屋属性：普通住宅建筑类型：小高层、高层开  发  商：深圳市悦峰投资有限公司投 资 商：佳兆业集团物业公司：佳兆业物业建筑设计...'},
        {value:'3',url:'4/3.jpg',title:'金融街南区融玺一期项目',text:'项目地址：惠州惠东县巽寮镇房屋属性：住宅建筑类型：顶级别墅，欧式自然开  发  商：金融街惠州置业有限公司园林单位：深圳市四季青园林股份有限公司 融玺项目位于金融街•巽寮湾...'}
      ],
      [
        {value:'4',url:'4/4.jpg',title:'佛山万科天傲湾',text:'项目地址：万科天傲湾花园位于佛山市顺德区新城区德胜河北岸房屋属性：住宅（豪宅）建筑类型：多层开  发  商：佛山市万科房地产有限公司园林单位：深圳市四季青园林股份有限公司...'},
        {value:'5',url:'4/5.jpg',title:'深圳湾壹号广场',text:'项目地址：深圳市南山区后海科苑大道与东滨路交界西北侧房屋属性：住宅（豪宅）建筑类型：多层开  发  商：深圳市鹏瑞地产开发有限公司园林单位：深圳市四季青园林股份有限公司	项...'},
        {value:'6',url:'4/6.jpg',title:'佛山万科金域蓝湾',text:'项目地址：佛山市南海区半岛路11号金域蓝湾项目房屋属性：住宅建筑类型：多层开  发  商：佛山市南海区万科金域蓝湾房地产有限公司园林单位：深圳市四季青园林股份有限公司	万科...'},
        {value:'7',url:'4/7.jpg',title:'北京孔子学院总部',text:'项目地址：北京市西城区物业类别：学校建筑类型：现代简约开  发  商：北教育部对外汉语教学发展中心园林单位：深圳市四季青园林股份有限公司	国家汉办是中国教育部直属事业单位...'},
      ]
    ]
  },
  detailList:{
    '1': [
      {head:'中山市盛世游艇',title:'第一～三标段',images:['0.png','1.png','2.png','3.png'],text:'<p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">项目名称：中山市吉宝置业神湾盛世游艇第一～三标段</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">甲方名称：盛世游艇会（中山）有限公司</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">项目地点：中山神湾</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">单方造价：462元/ ㎡</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">合同总金额： 18500000元</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">景观面积:40000㎡</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">施工时间：2016.9.02</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">项目业态类型：（综合体）</span></p>'},
      {head:'融创广深区域清远道申花园项目',title:'景观工程',images:['0.png','1.png','2.png','3.png','4.png','5.png','6.png','7.png','8.png','9.png'],text:'<p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">项目名称：融创广深区域清远道申花园项目景观工程</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">甲方名称：清远市道申房地产有限公司</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">项目地点：清远美林湖</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">单方造价：2000元/ ㎡</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">合同总金额： 14275878.89元</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">景观面积:7000㎡</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">施工时间：2017.09.29</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">项目业态类型：（住宅）</span></p>'},
      {head:'南沙中交',title:'',images:['0.png','1.png','2.png'],text:'<p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">项目名称：惠州奥园誉山湖项目住宅地块示范区园林工程</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">甲方名称：惠州市泰华房地产开发有限公司</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">项目地点：惠州湖心岛</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">单方造价：674元/ ㎡</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">合同总金额： 10108012.13元</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">景观面积:15000㎡</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">施工时间：2017.06.15</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">项目业态类型：（住宅）</span></p>'},
      {head:'惠州澳元誉山湖项目',title:'住宅地块示范区园林工程',images:['0.jpg','1.jpg','2.jpg','3.jpg','4.jpg','5.jpg'],text:'<p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">项目名称：惠州奥园誉山湖项目住宅地块示范区园林工程</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">甲方名称：惠州市泰华房地产开发有限公司</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">项目地点：惠州湖心岛</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">单方造价：674元/ ㎡</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">合同总金额： 10108012.13元</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">景观面积:15000㎡</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">施工时间：2017.06.15</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">项目业态类型：（住宅）</span></p>'},
      {head:'融创广深区域恒美花园',title:'清城首府',images:['0.png','1.png','2.png','3.png','4.png'],text:'<p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">项目名称：融创广深区域恒美花园（清城首府）</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">甲方名称：清远市恒美房地产开发有限。</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">项目地点：清远</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">单方造价：1200元/ ㎡</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">合同总金额： 5561589.93元</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">景观面积:4520㎡</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">施工时间：2017.08.05</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">项目业态类型：（住宅）</span></p>'},
      {head:'广州万达城室外主题乐园千年商都区园林',title:'景观工程',images:['0.jpg','1.jpg','2.jpg'],text:'<p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">项目名称：广州万达城室外主题乐园千年商都区园林景观工程</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">甲方名称：广州万达文化旅游城投资有限公司</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">项目地点：广州花都</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">单方造价：362元/ ㎡</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">合同总金额： 14479228.46元</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">景观面积:40000㎡</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">施工时间：2016.06.30</span></p><p style="margin-top:0pt;margin-bottom:0pt;direction:ltr;unicode-bidi:embed;vertical-align:baseline;">\t<span style="color:#999999;">项目业态类型：（主题乐园）</span></p>'}
    ],
    '4': [
      {head:'北京一号航站楼',title:'一层内庭院改造工程',images:['0.jpg','1.jpg','2.png'],text:'<p style="color:#999999;font-size:14px;line-height:22px;">\t<span style="font-weight:bold;">项目地址</span>：北京市朝阳区<br><span style="font-weight:bold;">物业类别</span>：机场<br><span style="font-weight:bold;">建筑类型</span>：现代简约<br><span style="font-weight:bold;">开&nbsp;&nbsp;发&nbsp;&nbsp;商</span>：北京首都国际机场股份有限公司<br><span style="font-weight:bold;">园林单位</span>：深圳市四季青园林股份有限公司</p><p style="color:#999999;font-size:14px;line-height:22px;">\t北京首都国际机场是“中国第一国门”，是中国最重要、规模最大、设备最先进、运输生产最繁忙的大型国际航空港。    在现代主义的基础上简约化处理，更突出现代主义中少就是多的理论，也称极简主义、几何式的直线条构成，以硬景为主，多用树阵点缀其中，对绿地进行切块处理，形成人流活动空间，突出交接节点的局部处理，对施工工艺要求高，适用于市政广场、滨河带、商业广场及青年人为主的现代住宅项目。</p>'},
      {head:'北京奥林匹克公园中区',title:'地下商业建筑下沉花园绿化工程',images:['0.jpg','1.jpg','2.jpg','3.jpg'],text:'<p style="color:#999999;font-size:14px;line-height:22px;">\t<span style="font-weight:bold;">项目地址</span>：北京市朝阳区<br><span style="font-weight:bold;">物业类别</span>：公园<br><span style="font-weight:bold;">建筑类型</span>：现代简约<br><span style="font-weight:bold;">开&nbsp;&nbsp;发&nbsp;&nbsp;商</span>：北京房修一建筑工程有限公司信诚智拓分公司<br><span style="font-weight:bold;">园林单位</span>：深圳市四季青园林股份有限公司</p><p style="color:#999999;font-size:14px;line-height:22px;">\t奥林匹克公园位于北京市朝阳区，地处北京城中轴线北端，总占地面积11.59平方千米，位于奥林匹克公园中心区地下9米的下沉花园其两侧是大型购物中心和地铁的出入口，长达700米的空间由7个庭院串联而成。下沉花园自南向北分别为1号院：御道宫门；2号院：古木花厅；3号院：礼乐重门；4、5号院：穿越瀛洲；6号院：合院趣；7号院：水印长天。7处庭院以中国元素为亮点，充分展示出中国历史与现代的文化传承。</p>'},
      {head:'佳兆业悦峰花园项目',title:'展示区园林景观绿化工程施工',images:['0.jpg','1.jpg','2.jpg'],text:'<p style="color:#999999;font-size:14px;line-height:22px;">\t<span style="font-weight:bold;">项目地址</span>：深圳市龙岗区布龙路与龙颈坳路交汇处<br><span style="font-weight:bold;">房屋属性</span>：普通住宅<br><span style="font-weight:bold;">建筑类型</span>：小高层、高层<br><span style="font-weight:bold;">开&nbsp;&nbsp;发&nbsp;&nbsp;商</span>：深圳市悦峰投资有限公司<br><span style="font-weight:bold;">投 资 商</span>：佳兆业集团<br><span style="font-weight:bold;">物业公司</span>：佳兆业物业<br><span style="font-weight:bold;">建筑设计单位</span>：城设（综合）建筑师事务所有限公司（方案），华森建筑与工程设计顾问有限公司（施工图）<br><span style="font-weight:bold;">园林设计单位</span>：贝尔高林国际（香港）有限公司（方案），深圳市海阳园林环境设计有限公司（施工图）<br><span style="font-weight:bold;">施工单位</span>：深圳市建工集团股份有限公司（土建），四季青园林股份有限公司</p><p style="color:#999999;font-size:14px;line-height:22px;">\t2014年已评风景园林获省金奖。</p>'},
      {head:'金融街南区融玺一期项目',title:'示范区园林景观工程',images:['nopic.jpg'],text:'<p style="color:#999999;font-size:14px;line-height:22px;">\t<span style="font-weight:bold;">项目地址</span>：惠州惠东县巽寮镇<br><span style="font-weight:bold;">房屋属性</span>：住宅<br><span style="font-weight:bold;">建筑类型</span>：顶级别墅，欧式自然<br><span style="font-weight:bold;">开&nbsp;&nbsp;发&nbsp;&nbsp;商</span>：金融街惠州置业有限公司<br><span style="font-weight:bold;">园林单位</span>：深圳市四季青园林股份有限公司</p><p style="color:#999999;font-size:14px;line-height:22px;">\t融玺项目位于金融街•巽寮湾南区，占地67.2万平方米，总建筑面积6.5万平方米，主力户型面积340-840平方米，规划容积率为0.14。是由金融街惠州置业有限公司精心打造的世界级滨海旅游圣地。集滨海娱乐、休闲度假、商务会议、生态观光、高尚运动、文化体验、健康养老、消闲居住等功能于一体的国家4A级滨海旅游景区。</p>'},
      {head:'佛山万科天傲湾项目',title:'展示区园建绿化工程',images:['0.jpg','1.jpg','2.jpg'],text:'<p style="color:#999999;font-size:14px;line-height:22px;">\t<span style="font-weight:bold;">项目地址</span>：万科天傲湾花园位于佛山市顺德区新城区德胜河北岸<br><span style="font-weight:bold;">房屋属性</span>：住宅（豪宅）<br><span style="font-weight:bold;">建筑类型</span>：多层<br><span style="font-weight:bold;">开&nbsp;&nbsp;发&nbsp;&nbsp;商</span>：佛山市万科房地产有限公司<br><span style="font-weight:bold;">园林单位</span>：深圳市四季青园林股份有限公司</p><p style="color:#999999;font-size:14px;line-height:22px;">\t万科天傲湾花园项目净占地面积约3.0万平方米，容积率2.5，计容积率建筑面积约7.6万平方米该展示区园建加绿化合同金额将近1500万元，我司从进驻场地到完工展示只用了1个月时间，无论是大局调配、细部处理、各种应急措施都充分展示我司在行业内的专业性。2014年已评获省银奖。</p>'},
      {head:'深圳湾壹号广场',title:'园林景观工程项目展示',images:['0.jpg','1.jpg'],text:'<p style="color:#999999;font-size:14px;line-height:22px;">\t<span style="font-weight:bold;">项目地址</span>：深圳市南山区后海科苑大道与东滨路交界西北侧<br><span style="font-weight:bold;">房屋属性</span>：住宅（豪宅）<br><span style="font-weight:bold;">建筑类型</span>：多层<br><span style="font-weight:bold;">开&nbsp;&nbsp;发&nbsp;&nbsp;商</span>：深圳市鹏瑞地产开发有限公司<br><span style="font-weight:bold;">园林单位</span>：深圳市四季青园林股份有限公司</p><p style="color:#999999;font-size:14px;line-height:22px;">\t项目定位是高档住宅（顶级豪宅），5月10日，在吉隆坡“2013年国际房地产奖”颁奖盛会上，深圳湾1号成功将“2013年国际地产亚太区公寓五星最高奖（5 Stars Best Apartment）”和“2013年国际地产亚太区最佳综合体奖（Highly Commended Mixed-use Development）”两项国际性大奖收入囊中。</p>'},
      {head:'佛山万科金域蓝湾',title:'园林景观工程项目展示',images:['0.jpg','1.jpg'],text:'<p style="color:#999999;font-size:14px;line-height:22px;">\t<span style="font-weight:bold;">项目地址</span>：佛山市南海区半岛路11号金域蓝湾项目<br><span style="font-weight:bold;">房屋属性</span>：住宅<br><span style="font-weight:bold;">建筑类型</span>：多层<br><span style="font-weight:bold;">开&nbsp;&nbsp;发&nbsp;&nbsp;商</span>：佛山市南海区万科金域蓝湾房地产有限公司<br><span style="font-weight:bold;">园林单位</span>：深圳市四季青园林股份有限公司</p><p style="color:#999999;font-size:14px;line-height:22px;">\t万科金域蓝湾处于“季华路总部第一街”上，是全国第12个金域蓝湾，占地面积约22万㎡，总建面约58万㎡。现代建筑立面，配以贝尔高林打造的特色东南亚风情园林，社区绿化率超5成。</p>'},
      {head:'孔子学院总部',title:'景观工程绿化工程',images:['0.jpg','1.jpg','2.jpg'],text:'<p style="color:#999999;font-size:14px;line-height:22px;">\t<span style="font-weight:bold;">项目地址</span>：北京市西城区<br><span style="font-weight:bold;">物业类别</span>：学校<br><span style="font-weight:bold;">建筑类型</span>：现代简约<br><span style="font-weight:bold;">开&nbsp;&nbsp;发&nbsp;&nbsp;商</span>：北教育部对外汉语教学发展中心<br><span style="font-weight:bold;">园林单位</span>：深圳市四季青园林股份有限公司</p><p style="color:#999999;font-size:14px;line-height:22px;">\t国家汉办是中国教育部直属事业单位，致力于为世界各国提供汉语言文化的教学资源和服务。图片中混凝土地砖美观、经济、实用，有不同块形。其设计灵活、简洁大方，通过图形组和和色彩搭配，充分体现了景观地面文化。</p>'}
      ]
  }
};

export default text;