const text = {
  minList:{
    "3":[
      [
        {value:'0',url:'3/0.png',title:'公司于2017年2月23日组织开展《卓越绩效管理》培训',time:'2017-04-10',text:'公司于2017年2月23日组织开展《卓越绩效管理》培训\t2017年2月23日，公司组织开展了一次以“走进卓越经营时代”为主题的“卓越绩效管理”培训，此次培训在总部会议室举行。\t培训特别邀请到深科投咨询的资深培训讲师——周永清老师，采用现场授课的形式，面对公司中、高层管理人员进行培训，旨在通过绩效管理，把员工聘...'}
      ]
    ]
  },
  detailList:{
    '3': [
      {head:'公司于2017年2月23日组织开展《卓越绩效管理》培训',title:'',time:'2017-04-10',images:['0.png','1.png'],text:'<p style="text-indent:2em;">\t<span style="font-size:16px;line-height:2;font-family:Microsoft YaHei;color:#999999;">2017年2月23日，公司组织开展了一次以“走进卓越经营时代”为主题的“卓越绩效管理”培训，此次培训在总部会议室举行。</span></p><p style="text-indent:2em;">\t<span style="font-size:16px;line-height:2;font-family:Microsoft YaHei;color:#999999;">培训特别邀请到深科投咨询的资深培训讲师——周永清老师，采用现场授课的形式，面对公司中、高层管理人员进行培训，旨在通过绩效管理，把员工聘用、职务升降、培训发展、薪酬福利等相结合，使得公司激励机制得到充分运用，提高中层以上管理人员的管理技能，推动公司绩效管理全面落实。参加此次培训的领导主要有：公司董事长周总，董事，监事，高级管理人员以及各二级部以上负责人，共二十二人。</span></p><p style="text-indent:2em;">\t<span style="font-size:16px;line-height:2;font-family:Microsoft YaHei;color:#999999;">此次培训通过对卓越绩效模式产生的背景、意义、框架及核心价值观等内容的讲解，了解了什么是卓越绩效；通过对绩效评分系统和评分指南的介绍，以及卓越绩效评价准则的运用，清楚了怎样通各种有效的方法来实现绩效的提升。在近四个小时的培训中，周老师与公司各领导学员积极交流和互动，运用理论与实际相结合的方式，针对我司现状进行了研讨和剖析，进一步提升的此次培训的实用性，周老师诙谐幽默的授课方式，让此次培训在轻松、愉快的氛围中成功举行。</span></p><p style="text-indent:2em;">\t<span style="font-size:16px;line-height:2;font-family:Microsoft YaHei;color:#999999;">培训结束后，公司董事长周总，结合本次培训的内容，以及公司目前存在的问题，进行了总结发言，并对后期的公司发展方向、公司愿景、以及近阶段工作重点进行了明确，周总的发言，犹如久旱逢甘霖，给参训人员注入了新的动力，大家信心满怀，纷纷表示，后期会多参加类似的培训，多学习，勤充电，与公司同成长，共奋进。</span></p>'}
    ]
  },
  tableList: [
    {
      id:0,name:'前台文员',education:'大专及以上',num:2,address:'深圳罗湖',time:'2017-09-28',detail:'<p style="MARGIN-TOP: 16px"><strong><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 21px; FONT-FAMILY: 宋体">任职要求</span></span></strong><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 21px; FONT-FAMILY: 宋体">：</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">1.&nbsp;&nbsp; </span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">中专或高中以上学历；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">2.&nbsp;&nbsp; </span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">形象好，气质佳，责任心强，有服务意识；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">3.&nbsp;&nbsp; </span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">能熟悉操作电脑，并能灵活运用办公软件；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">4. </span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">有较好的语言组织能力和沟通能力，有团队协作精神；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">5. </span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">有一年以上前台或文员工作经验；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">6. </span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 21px; FONT-FAMILY: 宋体">薪酬面议。</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 21px">7. </span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 21px; FONT-FAMILY: 宋体">有意者请发简历至：</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 21px">963399171@qq.com</span></span></p>'
    },
    {
      id:1,name:'会计核算主管',education:'大专及以上',num:2,address:'深圳罗湖',time:'2017-09-28',detail:' <p style="MARGIN-TOP: 16px"><strong><span style="FONT-SIZE: 21px; FONT-FAMILY: 宋体">工作内容</span></strong><span style="FONT-SIZE: 21px; FONT-FAMILY: 宋体">：</span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">1</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、参与会计核算和会计监督及财务管理工作；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">2</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、处理税务等相关事项；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">3</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、处理其他相关会计事项；</span></span></p><p><strong><span style="FONT-SIZE: 21px; FONT-FAMILY: 宋体">工作经验：</span></strong></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">1</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、有处理公司税务相关经验（税务专员者优先）；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">2</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、有上市公司特别是工程施工类上市公司经验者优先；</span></span></p><p><strong><span style="FONT-SIZE: 21px; FONT-FAMILY: 宋体">专业知识：</span></strong></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">1</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、财务等相关专业专科以上学历；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">2</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、有会计师或注册会计师资格者优先考虑；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">3</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、有会计证；</span></span></p><p><strong><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">薪酬面议。有意者请发简历至</span></span></strong><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">：</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">liqiang@four-season.com.cn</span></span></p>'
    },
    {
      id:2,name:'出纳员',education:'大专及以上',num:2,address:'深圳罗湖',time:'2017-09-28',detail:'<p style="MARGIN-TOP: 16px"><strong><span style="FONT-SIZE: 21px; FONT-FAMILY: 宋体">工作内容</span></strong><span style="FONT-SIZE: 21px; FONT-FAMILY: 宋体">：</span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">1</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、负责保管库存现金、有价证券、重要空白凭证、银行资金及银行账户的管理工作，具体执行公司资金管理制度和程序，支付各类款项；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">2</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、与银行等相关部门建立良好的沟通与协作关系；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">3</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、完成上级交给的其它事务性工作；</span></span></p><p><strong><span style="FONT-SIZE: 21px; FONT-FAMILY: 宋体">工作经验：</span></strong></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">1</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、有</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">2</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">年以上财会工作经历；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">2</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、有大中型企业出纳工作经验者优先；</span></span></p><p><strong><span style="FONT-SIZE: 21px; FONT-FAMILY: 宋体">专业知识：</span></strong></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">1</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、有会计证；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">2</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、财务等相关专业大专以上学历；</span></span></p><p><strong><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">薪酬面议。有意者请发简历至</span></span></strong><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">：</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">liqiang@four-season.com.cn</span></span></p>'
    },
    {
      id:3,name:'资料员',education:'大专及以上',num:2,address:'深圳罗湖',time:'2017-09-28',detail:'<p style="MARGIN-TOP: 16px"><strong><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 21px; FONT-FAMILY: 宋体">任职要求</span></span></strong><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 21px; FONT-FAMILY: 宋体">：</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">1</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、为人正直，工作踏实，做事认真，具有大专及以上学历，会计、统计、园林专业优先；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">2</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、熟悉</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">WORD</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">EXCEL</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">PPT</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">等办公软件；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">3</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、有良好的沟通协调能力，有一定的工作经验，有工地资料员工作经验者优先；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">4</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、公司办公为主，较少出差，但对数据勾稽关系要求较高；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">5</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、薪酬面议。</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">6</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">、有意者请发简历至：</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">1349781799@qq.com</span></span></p>'
    },
    {
      id:4,name:'预算员',education:'大专及以上',num:2,address:'深圳罗湖',time:'2017-09-28',detail:' <p style="MARGIN-TOP: 16px"><strong><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 21px; FONT-FAMILY: 宋体">任职要求</span></span></strong><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 21px; FONT-FAMILY: 宋体">：</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">1.&nbsp;&nbsp; </span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">工程造价、绿化工程类相关专业，大专以上学历；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">2.&nbsp;&nbsp; </span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">有现场结算经验者优先；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">3.&nbsp;&nbsp; </span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">熟悉地产园林及市政工程投标流程；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">4.&nbsp;&nbsp; </span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">熟练使用</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">CAD</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">等绘图软件、园林绿化工程量清单报价模式、熟练操作专业应用软件（如斯维尔、广联达）、熟悉工程图纸、能单独完成整个项目者优先；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">5.&nbsp; </span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">能够计算园林工程工程量；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">6.&nbsp; </span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">熟悉地产园林综合单价报价模式及计价方法；</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px">7.&nbsp; </span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 20px; FONT-FAMILY: 宋体">责任心强、较强的沟通协调能力、勤恳细致的工作作风，能承受工作压力，具有团队精神。</span></span></p><p><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 21px">8</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 21px; FONT-FAMILY: 宋体">、薪酬面议。有意者请发简历至：</span></span><span style="TEXT-DECORATION: underline"><span style="FONT-SIZE: 21px">348214992@qq.com</span></span></p>'
    }
  ]
};
export default text;