const text = {
  minList:{
    "1":[
      [
        {value:'0',url:'1/0.jpg',title:'新的起点，新的里程',time:'2018-04-09',text:'新的起点，新的里程    \t ——四季青携手中航里城共创辉煌    \t2018年1月29日，在中航集团总部召开的2017年交付质量评估会中，我公司荣获了“中航里城—2017年度景观交付品质奖”，这是继2015年获得“中航集团优秀合作单位奖”之后，获得的又一奖项，并且我司与中航合作的项目“中航...'},
        {value:'1',url:'1/1.jpg',title:'二十一世纪蓬勃发展，四季青精神砥砺前行',time:'2018-04-09',text:'二十一世纪蓬勃发展，四季青精神砥砺前行 \t  ——我公司连续...'},
        {value:'2',url:'1/2.png',title:'聚焦品质  携手同行',time:'2018-04-09',text:'聚焦品质  携手同行 ——四季青＆融创强强联合，再获殊荣   2017年12月1日，我司荣获融创中国广深区域第一届优秀供应商奖项。 自2017年8月以来我司与融创公司精诚合作，先后完成了融创广深区域清远恒美花园项目景观工程、融创广深区域佛山公司融腾湖滨曦园项目二期展示区商业街园林景观工程、融创...'}
      ],
      [
        {value:'3',url:'1/3.png',title:'抗洪救灾事迹',time:'2018-04-09',text:'深圳市四季青园林股份有限公司安徽分公司 抗洪救灾事迹   2016年7月16日，肥东县撮镇长临河发生洪水，由于遭遇连续两月降雨，造成水位猛涨、部分群众的房屋被淹、生产供电设备等受到损害；全县抗洪抢险形势严峻。面对洪灾，镇书记、镇领导展开布局，组织并率领人员抗洪抢险，四季青公司安徽分公司积极参与...'},
        {value:'4',url:'1/4.jpg',title:'强健身体，快乐工作！',time:'2017-04-10',text:'强健身体，快乐工作！\t                        ——记四季青特色企业文化\t2016年4月5日下午15:30分，四季青公司总部全体员工，在董事长周重的带领下，到笔架山集中步行锻炼身体。...'},
        {value:'5',url:'1/5.png',title:'公司于2017年2月23日组织开展《卓越绩效管理》培训',time:'2017-04-10',text:'公司于2017年2月23日组织开展《卓越绩效管理》培训\t2017年2月23日，公司组织开展了一次以“走进卓越经营时代”为主题的“卓越绩效管理”培训，此次培训在总部会议室举行。\t培训特别邀请到深科投咨询的资深培训讲师——周永清老师，采用现场授课的形式，面对公司中、高层管理人员进行培训，旨在通过绩效管理，把员工聘...'}
      ],
      [
        {value:'6',url:'1/6.jpg',title:'公司于2017年1月11日获得“深圳市知名品牌”',time:'2017-04-10',text:'公司于2017年1月11日获得“深圳市知名品牌”        2017年1月11日，经深圳市公证处现场公证，深圳知名品牌评价委员会审议，评选，确定，深圳市四季青园林股份有限公司等55家企业，入选“深圳知名品牌”。        深圳圳知名品牌...'}
      ]
    ]
  },
  detailList:{
    '1': [
      {head:'新的起点，新的里程',title:' ——四季青携手中航里城共创辉煌',time:'2018-04-09',images:['0.jpg'],text:'<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-indent:24.0000pt;text-align:justify;">\t2018年1月29日，在中航集团总部召开的2017年交付质量评估会中，我公司荣获了“中航里城—2017年度景观交付品质奖”，这是继2015年获得“中航集团优秀合作单位奖”之后，获得的又一奖项，并且我司与中航合作的项目“中航城国际社区（A区）B1地块园林绿化施工工程”在中航集团被评为第一名。</p><p class="MsoNormal" align="justify" style="text-align:left;margin-left:0pt;text-indent:24pt;">\t<span>自</span>2012年，我司与中航集团合作以来，都高质量地完成了中航城国际社区、中航紫金广场的园建绿化施工工作，在得到中航集团信任的同时，也受到了业主们的一致好评。</p><p class="MsoNormal" align="justify" style="text-align:left;margin-left:0pt;text-indent:24pt;">\t相信未来，我们还会有更多合作的机会，一起携手，寻找下一个起点，开启下一段里程。 </p>'},
      {head:'二十一世纪蓬勃发展，四季青精神砥砺前行',title:' ——我公司连续多年获得广东省优秀园林企业',time:'2018-04-09',images:['0.jpg','1.jpg'],text:'<p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-indent:24.0000pt;text-align:justify;">\t2018<span>年</span><span>1</span><span>月</span><span>19</span><span>日（星期五）下午</span><span>14</span><span>：</span><span>30</span><span>在珠海国际会展中心召开的</span><span>2017</span><span>年广东省风景园林协会会员大会中，我公司荣获了</span><span>2015-2016</span><span>年度广东省优秀园林企业二十强的称号</span>。</p><p class="MsoNormal" align="justify" style="margin-left:0.0000pt;text-indent:24.0000pt;text-align:justify;">\t迄今为止，我公司已<span>连续获得了</span>2011-2012<span>年度广东优秀园林企业、</span><span>2013-2014</span><span>年度广东省优秀园林企业以及</span><span>2015-2016</span><span>年度广东省优秀园林企业，尤其</span>在2017<span>年的评奖工作中，</span>我司<span>表现尤其突出，在全省几百家参与评奖的单位中跻身前二十，荣获了</span>2015-2016<span>年度广东省优秀园林企业二十强的称号，这不仅反映了业界对我司的认可，更彰显了我司在对待每一个工程的时候，都严把质量关，继承老四季青人的传统，发扬新四季青人的独具匠心，力争把每一个工程都做到最好的匠心精神。</span> </p><p class="MsoNormal" align="justify" style="text-align:left;margin-left:0pt;text-indent:24pt;">\t回首过去，激情澎湃，放眼未来，砥砺前行。希望在新的<span>一年，我们依旧秉承优良传统，</span>“撸起袖子加油干”，争做业界的领头羊！</p>'},
      {head:'聚焦品质 携手同行',title:' ——四季青＆融创强强联合，再获殊荣',time:'2018-04-09',images:['0.png','1.png','2.png'],text:'<p class="MsoNormal" align="justify" style="text-align:left;margin-left:0pt;text-indent:28pt;">\t2017<span>年</span><span>12</span><span>月</span><span>1</span><span>日，我司荣获融创中国广深区域第一届优秀供应商奖项。</span> </p><p class="MsoNormal" align="justify" style="text-align:left;margin-left:0pt;text-indent:28pt;">\t<span>自</span>2017<span>年</span><span>8</span><span>月以来我司与融创公司精诚合作，先后完成了融创广深区域清远恒美花园项目景观工程、融创广深区域佛山公司融腾湖滨曦园项目二期展示区商业街园林景观工程、融创广深区域东莞公司大岭山君澜花园大区景观工程施工合同等</span><span>13</span><span>个项目。经过公司各部门的紧密合作和不懈努力，我司获得融创中国广深区域第一届优秀供应商奖，能赢得此殊荣，离不开公司一线员工夜以继日的辛苦和开拓。相信，未来的我们，与融创携手同行，一定会创造出更多辉煌的业绩。</span> </p>'},
      {head:'深圳市四季青园林股份有限公司安徽分公司',title:' 抗洪救灾事迹',time:'2018-04-09',images:['0.png','1.png','2.png'],text:'<p class="MsoNormal" align="justify" style="text-align:left;margin-left:0pt;text-indent:28pt;">\t2016年7月16日，肥东县撮镇长临河发生洪水，由于遭遇连续两月降雨，造成水位猛涨、部分群众的房屋被淹、生产供电设备等受到损害；全县抗洪抢险形势严峻。面对洪灾，镇书记、镇领导展开布局，组织并率领人员抗洪抢险，四季青公司安徽分公司积极参与，迅速组成抗洪抢险队伍，开展抗洪救灾工作，有效控制了洪水灾情，得到了广大群众与镇政府的称赞和认可。</p>'},
      {head:'强健身体，快乐工作！',title:'——记四季青特色企业文化',time:'2017-04-10',images:['0.jpg','1.jpg','2.jpg','3.jpg','4.jpg'],text:'<p style="text-indent:2em;">\t<span style="font-family:Microsoft YaHei;color:#999999;"><span style="font-size:16px;">2</span><span style="line-height:2;font-size:16px;">016年4月5日下午15:30分，四季青公司总部全体员工，在董事长周重的带领下，到笔架山集中步行锻炼身体。</span></span></p><p style="text-indent:2em;">\t<span style="font-family:Microsoft YaHei;color:#999999;"><span style="line-height:2;font-size:16px;">您可能有这样的疑问：“这个时间，锻炼身体？公司搞活动？”</span></span></p><p style="text-indent:2em;">\t<span style="font-family:Microsoft YaHei;color:#999999;"><span style="line-height:2;font-size:16px;">其实，这是四季青公司独创的特色企业文化之一。</span></span></p><p style="text-indent:2em;">\t<span style="font-family:Microsoft YaHei;color:#999999;"><span style="line-height:2;font-size:16px;">四季青公司自2016年4月5日起，定于每周的周一至周五下午15:30到17:30为步行锻炼时间，提倡全体员工合理安排工作时间，提高工作效率，充分利用下午的两小时，进行步行锻炼，强健身体！</span></span></p><p style="text-indent:2em;">\t<span style="font-family:Microsoft YaHei;color:#999999;"><span style="line-height:2;font-size:16px;">倡导员工开展步行健身运动的，正是四季青公司董事长周重先生，周董平时热爱运动，在得益于步行锻炼带来的身体健康之后，周董体恤到员工的身体健康，呼吁大家勤锻炼，多运动，把对员工的关爱，实施到行动中，让全体员工切身感受到了周总如亲人般的关怀，感受到了公司如家庭般的温暖。</span></span></p><p style="text-indent:2em;">\t<span style="font-family:Microsoft YaHei;color:#999999;"><span style="line-height:2;font-size:16px;">如今，四季青公司步行健身运动已持续一年了，员工们早已习惯这种运动方式，每当下午时分，在笔架山蜿蜒的小路上，在幽静的登山道，在古典的小亭前，或独自疾走，或结伴慢步，或停步小憩，那一个个快乐的身影，就是四季青人。通过一年的锻炼，大家面色红润，神清气爽，健步如飞，身体越来越健康。</span></span></p><p style="text-indent:2em;">\t<span style="font-family:Microsoft YaHei;color:#999999;"><span style="line-height:2;font-size:16px;">在深圳这座年轻的城市，在这竞争激烈的时代，试问有几家私企老板能如此慷慨？如此有气魄？</span></span><span style="color:#999999;font-family:\'Microsoft YaHei\';font-size:16px;line-height:2;">与人玫瑰，手留余香；赠人健康，功德无量。敢为天下先，唯有周董！</span></p>'},
      {head:'公司于2017年2月23日组织开展《卓越绩效管理》培训',title:'',time:'2017-04-10',images:['0.png','1.png'],text:'<p style="text-indent:2em;">\t<span style="font-size:16px;line-height:2;font-family:Microsoft YaHei;color:#999999;">2017年2月23日，公司组织开展了一次以“走进卓越经营时代”为主题的“卓越绩效管理”培训，此次培训在总部会议室举行。</span></p><p style="text-indent:2em;">\t<span style="font-size:16px;line-height:2;font-family:Microsoft YaHei;color:#999999;">培训特别邀请到深科投咨询的资深培训讲师——周永清老师，采用现场授课的形式，面对公司中、高层管理人员进行培训，旨在通过绩效管理，把员工聘用、职务升降、培训发展、薪酬福利等相结合，使得公司激励机制得到充分运用，提高中层以上管理人员的管理技能，推动公司绩效管理全面落实。参加此次培训的领导主要有：公司董事长周总，董事，监事，高级管理人员以及各二级部以上负责人，共二十二人。</span></p><p style="text-indent:2em;">\t<span style="font-size:16px;line-height:2;font-family:Microsoft YaHei;color:#999999;">此次培训通过对卓越绩效模式产生的背景、意义、框架及核心价值观等内容的讲解，了解了什么是卓越绩效；通过对绩效评分系统和评分指南的介绍，以及卓越绩效评价准则的运用，清楚了怎样通各种有效的方法来实现绩效的提升。在近四个小时的培训中，周老师与公司各领导学员积极交流和互动，运用理论与实际相结合的方式，针对我司现状进行了研讨和剖析，进一步提升的此次培训的实用性，周老师诙谐幽默的授课方式，让此次培训在轻松、愉快的氛围中成功举行。</span></p><p style="text-indent:2em;">\t<span style="font-size:16px;line-height:2;font-family:Microsoft YaHei;color:#999999;">培训结束后，公司董事长周总，结合本次培训的内容，以及公司目前存在的问题，进行了总结发言，并对后期的公司发展方向、公司愿景、以及近阶段工作重点进行了明确，周总的发言，犹如久旱逢甘霖，给参训人员注入了新的动力，大家信心满怀，纷纷表示，后期会多参加类似的培训，多学习，勤充电，与公司同成长，共奋进。</span></p>'},
      {head:'公司于2017年1月11日获得“深圳市知名品牌”',title:'',time:'2017-04-10',images:['0.png'],text:'<p><span style="font-size:16px;font-family:Microsoft YaHei;color:#999999;line-height:2;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2017年1月11日，经深圳市公证处现场公证，深圳知名品牌评价委员会审议，评选，确定，深圳市四季青园林股份有限公司等55家企业，入选“深圳知名品牌”。</span></p><p><span style="font-size:16px;font-family:Microsoft YaHei;color:#999999;line-height:2;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;深圳圳知名品牌评价委员会于2016年5月17日，发起了第十四届“深圳知名品牌”评价活动，我司积极参选，在历时6个月的评选中，公司全体人员空前团结，各部门及时响应，全力配合。在各级领导的倾情动员下，公司全体员工众志成城，积极参与投票宣传活动，经过全体员工的共同努力，公司取得了公众投票第三名的好成绩。</span></p><p><span style="font-size:16px;font-family:Microsoft YaHei;color:#999999;line-height:2;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;通过企业申报、社会公众投票、企业内部管理体系现场评审、品牌价值评估和行业专家评价等评审工作的开展，公司最终获得第十四届“深圳知名品牌”荣誉称号，实至名归。</span></p>'},
    ]
  }
};
export default text;